only_rules: #only the rules we want
  ### Auto correctable rules ###
  - colon
  - comma
  - closing_brace
  - closure_spacing
  - custom_rules
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - file_header
  - implicit_return
  - joined_default_parameter
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - legacy_multiple
  - mark
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - private_over_fileprivate
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_void_return
  - return_arrow_whitespace
  - statement_position
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - vertical_whitespace
  - toggle_bool
  - sorted_imports
  - void_return


excluded: # paths to ignore during linting. Takes precedence over `included`.
# Some of the paths are commented because they are block and overload the linting process due to a bug of swiftlint
  - ./DerivedData/
  # - "**/*/DerivedData/"
  # - "**/*/Package.swift"
  # - "**/*/.build"
  # - "**/*/*_generated.swift"

allow_zero_lintable_files: true

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
